{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "target": "thumbv8m.main-none-eabihf",
          "allTargets": false,
          "features": [
            "defmt",
            "defmt-rtt",
            "embassy-rp/defmt",
            "panic-probe/defmt",
            "panic-halt",
            "cortex-m-semihosting",
            "panic-semihosting"
          ]
        },
        "check": {
          "allTargets": false,
          "features": [
            "defmt",
            "defmt-rtt",
            "embassy-rp/defmt",
            "panic-probe/defmt",
            "panic-halt",
            "cortex-m-semihosting",
            "panic-semihosting"
          ]
        }
      }
    }
  }
}
