[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
rustflags = [
    "-C", "link-arg=--cref",
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-L", ".",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
